### ISSUE TITLE
Audio Issue - SDL Mixer Self Compiling issue

### ISSUE THREAD

**Issue by aneury1** [aneury1/DOEngine#29]
there is one issue when try to compile, pulled version of SDL_Mixer, it seems that we can Find LibAlsa or LibSound.
we need to take action on this because some system does not provide those by default, we need to create variables to allows developer who compiles the library to adapt to theirs by leave them choice between own installed SDLX version or Self compile Version, what I propose is create a flag on CMake so they can turn On or Off depending on their wished.

here is the relevant trace to the error.

```
INFO: SDL_Init Error: dsp: No such audio device
[1]    18311 segmentation fault (core dumped)  ./DOENGINE-sample
```

[here is a topic regarding to the error](https://discourse.libsdl.org/t/couldnt-open-audio-device-no-available-audio-device/18499 )

my propose Variable name:
`set(SDL2_SELF_COMPILING TRUE) `

if accepted I could put on my own and push to the repo.

**Comment by victordmontero** [comment]
You could try that solution. However, I think that will not solve the underlying problem with the audio

**Comment by victordmontero** [comment]
Can you try setting this option to `ON`: `SDL_ALSA` on CMake?

**Comment by aneury1** [comment]
it worked
